### PR TITLE
DIG-1416: Add intervals support

### PR DESCRIPTION
**Pull request by OrdiNeu**
- Add support for katsu data intervals by using data_of_birth from Donor directly
- For testing, pull this query into candigv2, should pass test-integration

### CODE REVIEW

**Comment by mshadbolt** [comment]
rebased so that it would build properly

**Comment by mshadbolt** [comment]
Confirmed integration tests pass and the graph on the search page loads and the age at diagnosis graph updates when filters are used. 

Are the object object errors in the clinical data table for date of birth and date of death an error on query or because data portal needs updating?

Screenshot 2024-02-08 at 1 04 51 PM

**Comment by OrdiNeu** [comment]
@mshadbolt 
> Are the object object errors in the clinical data table for date of birth and date of death an error on query or because data portal needs updating?

Those are fixed that need to happen on the data portal side (it needs to go from date->interval, and read the object)

**Review by mshadbolt — APPROVED** [review]
Looks good to me!

**Review by SonQBChau — APPROVED** [review]

**Comment by mshadbolt** [comment]
hang on francis is checking something

**Comment by OrdiNeu** [comment]
Looks good to me now too :heavy_check_mark:

**Pull request merged**
