### PR TITLE
DIG-1372: Query can assemble discovery queries

### PR DESCRIPTION
**Pull request by OrdiNeu**
# Description
[DIG-1372](https://candig.atlassian.net/browse/DIG-1372)

This creates another new endpoint: `/discovery/query`, that takes all the same arguments and logic as `/query` but returns counts only, and does so with elevated priviledges.

# To Test:
1. Test the endpoint with no authorization: `curl candig.docker.internal:1236/discovery/query`
2. Add a primary site and ensure that it returns just the donor with that (1 result): `curl candig.docker.internal:1236/discovery/query?primary_site=Esophagus`
3. Add multiple primary sites and ensure it returns donors with either one (2 results): `curl "candig.docker.internal:1236/discovery/query?primary_site=Esophagus&primary_site=Gallbladder"`
4. Add multiple clinical parameters and ensure it correctly parses the donor that has both (1 result): `curl "candig.docker.internal:1236/discovery/query?primary_site=Gallbladder&treatment=Immunotherapy"`
5. Add a genomic parameter and ensure it correctly parses it: (1 result): `curl candig.docker.internal:1236/discovery/query?chrom=chr21:5030000-5030847`
6. Add both, make sure it parses that properly

[DIG-1372]: https://candig.atlassian.net/browse/DIG-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kcranston** [comment]
Apologies for this, but can you split this into two PRs - one that incorporates the discovery query cross-referencing (to be merged first) and one that incorporates the aggregation limit? I would like to have the flexibility of being able to merge discovery queries into stable for the demo even if we aren't ready to merge aggregation limits (because that also requires data portal changes).

**Comment by OrdiNeu** [comment]
Sure thing, I've removed the censoring bit and have just the discovery query fixes in here :heavy_check_mark:

**Review by daisieh — COMMENTED** [review]
I'm not sure if this is correct behavior or not:

I tried the genomic param as you said, and it looked like this:
```
(candig) daisieh2019:CanDIGv2$ curl candig.docker.internal:1236/discovery/query?chrom=chr21:5030000-5030847
{
  "age_at_diagnosis": {
    "30-39": 1
  },
  "cancer_type_count": {
    "Eye and adnexa": 1
  },
  "patients_per_cohort": {
    "SYNTHETIC-2": 1
  },
  "treatment_type_count": {
    "Chemotherapy": 1,
    "Immunotherapy": 1,
    "Surgery": 1
  }
}
```

I then added the clinical param back, and I chose Immunotherapy, since that one is clearly in the results:
```
(candig) daisieh2019:CanDIGv2$ curl candig.docker.internal:1236/discovery/query?chrom=chr21:5030000-5030847&treatment=Immunotherapy
{
  "age_at_diagnosis": {
    "30-39": 1
  },
  "cancer_type_count": {
    "Eye and adnexa": 1
  },
  "patients_per_cohort": {
    "SYNTHETIC-2": 1
  },
  "treatment_type_count": {
    "Chemotherapy": 1,
    "Immunotherapy": 1,
    "Surgery": 1
  }
}
```
Am I supposed to get all the other treatment type counts as well? Maybe I am, since they're all for the same patient?

**Comment by kcranston** [comment]
Yes, this is the expected behaviour., assuming that the patient had all three treatment types.

**Comment by kcranston** [comment]
~Does the result not also include a simple count of the number of matching patients?~ nm, that's the `patients_per_cohort`.

**Comment by daisieh** [comment]
I think the patients_per_cohort does that?

**Review by daisieh — APPROVED** [review]
This looks good to me now.

**Comment by OrdiNeu** [comment]
Had to rebase it

**Pull request merged**
